// <auto-generated />
using System;
using AboneYonetim.WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AboneYonetim.WebAPI.Migrations
{
    [DbContext(typeof(AboneYonetimContext))]
    [Migration("20210917062503_ilk")]
    partial class ilk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AboneYonetim.Entities.Concrete.ABONE", b =>
                {
                    b.Property<int>("ObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AboneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int?>("Du_KullaniciID")
                        .HasColumnType("int");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DuzeltmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Ka_KullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KayitTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<int?>("Sil_KullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SilmeTarih")
                        .HasColumnType("datetime2");

                    b.HasKey("ObjectID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("ABONELER");
                });

            modelBuilder.Entity("AboneYonetim.Entities.Concrete.FATURA", b =>
                {
                    b.Property<int>("ObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AboneID")
                        .HasColumnType("int");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int?>("Du_KullaniciID")
                        .HasColumnType("int");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DuzeltmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("FaturaDonemi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaturaNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FaturaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Ka_KullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KayitTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<bool>("Odendi")
                        .HasColumnType("bit");

                    b.Property<int?>("Sil_KullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SilmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SonOdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ObjectID");

                    b.HasIndex("AboneID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("FATURALAR");
                });

            modelBuilder.Entity("AboneYonetim.Entities.Concrete.KULLANICI", b =>
                {
                    b.Property<int>("ObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int?>("Du_KullaniciID")
                        .HasColumnType("int");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DuzeltmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GsmNo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("Ka_KullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KayitTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kulad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RolID")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Sil_KullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SilmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("TcNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("ObjectID");

                    b.HasIndex("RolID");

                    b.ToTable("KULLANICILAR");
                });

            modelBuilder.Entity("AboneYonetim.Entities.Concrete.KULLANICI_ROL", b =>
                {
                    b.Property<int>("ObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int?>("Du_KullaniciID")
                        .HasColumnType("int");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DuzeltmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Ka_KullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KayitTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("RolAd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Sil_KullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SilmeTarih")
                        .HasColumnType("datetime2");

                    b.HasKey("ObjectID");

                    b.ToTable("KULLANICI_ROLLER");
                });

            modelBuilder.Entity("AboneYonetim.Entities.Concrete.TAHSILAT", b =>
                {
                    b.Property<int>("ObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AboneID")
                        .HasColumnType("int");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int?>("Du_KullaniciID")
                        .HasColumnType("int");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DuzeltmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("FaturaID")
                        .HasColumnType("int");

                    b.Property<int?>("Ka_KullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KayitTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Sil_KullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SilmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TahsilatTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ObjectID");

                    b.HasIndex("AboneID");

                    b.HasIndex("FaturaID");

                    b.ToTable("TAHSILATLAR");
                });

            modelBuilder.Entity("AboneYonetim.Entities.Concrete.TAHSILAT_DETAY", b =>
                {
                    b.Property<int>("ObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int?>("Du_KullaniciID")
                        .HasColumnType("int");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DuzeltmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("FaturaID")
                        .HasColumnType("int");

                    b.Property<int?>("Ka_KullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KayitTarih")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OdendiMi")
                        .HasColumnType("bit");

                    b.Property<int?>("Sil_KullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SilmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("TahsilatID")
                        .HasColumnType("int");

                    b.HasKey("ObjectID");

                    b.HasIndex("FaturaID");

                    b.HasIndex("TahsilatID");

                    b.ToTable("TAHSILAT_DETAYLAR");
                });

            modelBuilder.Entity("AboneYonetim.Entities.Concrete.ABONE", b =>
                {
                    b.HasOne("AboneYonetim.Entities.Concrete.KULLANICI", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("AboneYonetim.Entities.Concrete.FATURA", b =>
                {
                    b.HasOne("AboneYonetim.Entities.Concrete.ABONE", "Abone")
                        .WithMany("Faturalar")
                        .HasForeignKey("AboneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AboneYonetim.Entities.Concrete.KULLANICI", "Kullanici")
                        .WithMany("lstFaturalar")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abone");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("AboneYonetim.Entities.Concrete.KULLANICI", b =>
                {
                    b.HasOne("AboneYonetim.Entities.Concrete.KULLANICI_ROL", "KullaniciRol")
                        .WithMany("lstKullanicilar")
                        .HasForeignKey("RolID");

                    b.Navigation("KullaniciRol");
                });

            modelBuilder.Entity("AboneYonetim.Entities.Concrete.TAHSILAT", b =>
                {
                    b.HasOne("AboneYonetim.Entities.Concrete.ABONE", "Abone")
                        .WithMany("Tahsilatlar")
                        .HasForeignKey("AboneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AboneYonetim.Entities.Concrete.FATURA", "Fatura")
                        .WithMany()
                        .HasForeignKey("FaturaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abone");

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("AboneYonetim.Entities.Concrete.TAHSILAT_DETAY", b =>
                {
                    b.HasOne("AboneYonetim.Entities.Concrete.FATURA", "Fatura")
                        .WithMany()
                        .HasForeignKey("FaturaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AboneYonetim.Entities.Concrete.TAHSILAT", "Tahsilat")
                        .WithMany()
                        .HasForeignKey("TahsilatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fatura");

                    b.Navigation("Tahsilat");
                });

            modelBuilder.Entity("AboneYonetim.Entities.Concrete.ABONE", b =>
                {
                    b.Navigation("Faturalar");

                    b.Navigation("Tahsilatlar");
                });

            modelBuilder.Entity("AboneYonetim.Entities.Concrete.KULLANICI", b =>
                {
                    b.Navigation("lstFaturalar");
                });

            modelBuilder.Entity("AboneYonetim.Entities.Concrete.KULLANICI_ROL", b =>
                {
                    b.Navigation("lstKullanicilar");
                });
#pragma warning restore 612, 618
        }
    }
}
